# Generated by Django 3.2.15 on 2022-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(default="User", max_length=80),
        ),
    ]
